TARGET = iphone:clang:8.1
include theos/makefiles/common.mk

APPLICATION_NAME = App
App_FILES = main.m AppApplication.mm RootViewController.mm
App_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
